import type { TileKind } from '../shared/types';
import { WORLD_TERRAINS } from '../shared/world-schema';
import { NPC_CATALOG } from '../shared/npcs';
export const field = (id: string, label: string, type = 'number', step = '1') => `<label>${label}<input id="${id}" type="${type}" step="${step}"></label>`;
export const terrains: Record<TileKind, {
    name: string;
    color: string;
}> = { grass: { name: 'Erba', color: '#73865a' }, path: { name: 'Strada', color: '#b6a17b' },
    water: { name: 'Acqua', color: '#507d91' }, rock: { name: 'Roccia', color: '#555e55' }, bush: { name: 'Cespuglio', color: '#486b42' },
    mud: { name: 'Fango', color: '#796b51' }, snow: { name: 'Neve', color: '#d1dcd5' }, ice: { name: 'Ghiaccio', color: '#a0c7ce' } };
export const tools = [['select', '↖', 'Seleziona'], ['terrain', '▦', 'Terreno'], ['asset', '♧', 'Asset'], ['erase', '⌫', 'Cancella'], ['restore', '↺', 'Procedurale'], ['zone', '▱', 'Zona'], ['npc', '♙', 'Spawn NPC'], ['dungeon', '♜', 'Dungeon'], ['spawn', '⌖', 'Spawn player']] as const;
export const worldMakerLayout = `<header><span class="brand-mark">◈</span><div class="brand"><h1>World Maker</h1><p>RIFTLANDS / WORLD AUTHORING</p></div><span class="badge">LOCALE</span><div class="top-actions"><a href="/dungeon-maker.html">Dungeon Maker ↗</a><button id="reload">Ricarica progetto</button><button id="import-world">Importa</button><button id="export-world">Esporta</button><button id="apply-world" class="primary">Applica al gioco</button></div></header>
<main><aside><section><h2>01 · Strumenti</h2><div class="tool-grid">${tools.map(([id, icon, name]) => `<button data-tool="${id}"><span>${icon}</span>${name}</button>`).join('')}</div><div class="fields" style="margin-top:12px"><label>Terreno<select id="terrain">${WORLD_TERRAINS.map(t => `<option value="${t}">${terrains[t].name}</option>`).join('')}</select></label><div class="pair">${field('brush-radius', 'Raggio pennello')}${field('brush-density', 'Densità %')}</div><label class="check"><input id="mass" type="checkbox">Asset con pennello continuo</label></div><p class="hint">Trascina per dipingere. Ctrl + trascina: asset in massa. Spazio + trascina o tasto centrale: sposta la vista. Rotella: zoom.</p></section>
<section><h2>02 · Catalogo asset</h2><button id="import-assets" class="wide">＋ Importa PNG / SVG</button><input id="asset-search" placeholder="Cerca un asset…" aria-label="Cerca asset"><div id="asset-list" class="asset-list"></div></section>
<section><h2>03 · Contenuti</h2><label>Dungeon installato<select id="dungeon"></select></label><p class="hint">Il dungeon resta definito nel suo maker. Qui ne sposti l’istanza completa.</p><label>NPC manuale<select id="npc">${Object.entries(NPC_CATALOG).map(([id, n]) => `<option value="${id}">${n.name}</option>`).join('')}</select></label><label>Tipo di zona<select id="zone-template"><option value="climate">Clima e generazione</option><option value="safe">Senza PvP</option><option value="pvp">PvP</option><option value="arena">Ingresso arena</option><option value="population">Popolazione NPC</option></select></label><p class="hint">Trascina un rettangolo, poi modifica le regole. Le zone possono sovrapporsi.</p></section></aside>
<section class="workspace"><div class="map-toolbar"><button id="undo" title="Ctrl+Z">↶</button><button id="redo" title="Ctrl+Shift+Z">↷</button><strong id="tool-label">Seleziona</strong><button id="home">Origine</button><button id="goto">Vai a…</button><button id="zoom-out">−</button><span id="zoom-label">100%</span><button id="zoom-in">＋</button><button id="properties-toggle">☷</button></div><div class="viewport"><canvas id="map" tabindex="0" aria-label="Mappa del mondo modificabile"></canvas><span class="map-note">MONDO PROCEDURALE · NESSUN LIMITE DI MAPPA PREFISSATO</span><span id="coordinates" class="map-coordinate">X 0 · Y 0</span></div><div class="map-footer"><label><input id="show-grid" type="checkbox" checked>Griglia</label><label><input id="show-zones" type="checkbox" checked>Zone</label><label><input id="show-cells" type="checkbox">Collisioni / visibilità</label><label><input id="show-npcs" type="checkbox">NPC generati</label><span id="map-info"></span></div></section>
<aside class="inspector"><section id="asset-inspector" hidden><h2>Asset <span class="pill">CATALOGO</span></h2><div class="fields">${field('asset-name', 'Nome', 'text')}<label>Aspetto<select id="asset-visual"><option value="image">Immagine importata</option><option value="brazier">Braciere animato</option><option value="campfire">Fuoco da campo animato</option></select></label><div class="pair">${field('asset-width', 'Larghezza · caselle', 'number', '.25')}${field('asset-height', 'Altezza · caselle', 'number', '.25')}</div><label class="check"><input id="keep-ratio" type="checkbox" checked>Mantieni proporzioni</label><div class="pair"><label>Disegno<select id="asset-layer"><option value="ground">Sfondo</option><option value="object">Oggetto</option></select></label>${field('asset-pivot', 'Base per ordine disegno · 0–1', 'number', '.05')}</div></div><button id="asset-update" class="wide" style="margin-top:10px">Aggiorna asset</button><p class="hint">La scala vale per tutte le istanze. Le nuove celle sono calpestabili; le proprietà esistenti restano conservate.</p><canvas id="asset-grid" class="asset-grid" aria-label="Proprietà per quadratino dell’asset"></canvas><div class="pair"><label>Movimento<select id="cell-blocked"><option value="false">Calpestabile</option><option value="true">Bloccante</option></select></label><label>Visibilità<select id="cell-visibility"><option value="normal">Normale</option><option value="hide">Nascondiglio</option><option value="fade">Trasparente al passaggio</option></select></label></div><button id="fill-cells" class="wide" style="margin-top:8px">Applica a tutte le celle</button><p class="hint">Clicca o trascina sui quadratini per assegnare movimento e visibilità insieme.</p><div class="legend"><span><i style="background:#dd876a"></i>Blocco</span><span><i style="background:#adca74"></i>Nascondiglio</span><span><i style="background:#8acddd"></i>Trasparenza</span></div>
<h3>Generatore del mondo</h3><div class="fields"><label class="check"><input id="gen-enabled" type="checkbox">Disponibile alla generazione</label>${field('gen-category', 'Categoria', 'text')}<div class="pair">${field('gen-temp-min', 'Temperatura min · 0–1', 'number', '.01')}${field('gen-temp-max', 'Temperatura max · 0–1', 'number', '.01')}${field('gen-moist-min', 'Umidità min · 0–1', 'number', '.01')}${field('gen-moist-max', 'Umidità max · 0–1', 'number', '.01')}${field('gen-density', 'Frequenza %')}${field('gen-spacing', 'Distanza minima · celle')}</div><div id="gen-terrains" class="tool-grid"></div><button id="gen-update">Aggiorna regole</button></div><p class="hint">Le regole vengono verificate su tutto l’ingombro. La frequenza vale per gli slot della propria fascia di dimensioni; gli asset grandi non diradano tutto il catalogo. Le sovrapposizioni vengono risolte in modo deterministico.</p><button id="asset-delete" class="wide danger">Rimuovi asset e sue istanze</button></section>
<section id="selection-inspector" hidden><h2 id="selection-title">Selezione</h2><div id="selection-fields" class="fields"></div><div class="property-actions"><button id="selection-update">Aggiorna</button><button id="selection-delete" class="danger">Rimuovi</button></div></section>
<section id="zone-inspector" hidden><h2>Regole zona</h2><div class="fields">${field('zone-name', 'Nome', 'text')}${field('zone-priority', 'Priorità')}<label>Forma<select id="zone-shape"><option value="rect">Rettangolo</option><option value="circle">Cerchio</option></select></label><div class="pair">${field('zone-x', 'X · celle', 'number', '.01')}${field('zone-y', 'Y · celle', 'number', '.01')}${field('zone-width', 'Larghezza / raggio', 'number', '.01')}${field('zone-height', 'Altezza')}</div><div class="pair">${field('zone-temperature', 'Temperatura · vuoto = genera', 'number', '.01')}${field('zone-moisture', 'Umidità · vuoto = genera', 'number', '.01')}</div><label>PvP<select id="zone-pvp"><option value="">Eredita</option><option value="false">Disabilitato</option><option value="true">Abilitato</option></select></label><label>Asset procedurali<select id="zone-generation"><option value="">Eredita</option><option value="true">Abilitati</option><option value="false">Disabilitati</option></select></label>${field('zone-arena', 'Arena · vuoto = nessuna', 'text')}<label class="check"><input id="zone-npcs" type="checkbox">Definisci popolazione NPC</label><div class="pair">${field('zone-density', 'Probabilità spawn %')}${field('zone-limit', 'Limite NPC / chunk')}${field('zone-slime', 'Gelatine %')}${field('zone-wisp', 'Fuochi fatui %')}${field('zone-sentinel', 'Guardiani %')}</div><button id="zone-update">Aggiorna zona</button><button id="zone-delete" class="danger">Rimuovi zona</button></div><p class="hint">Prevale la priorità più alta, per ciascuna proprietà; a parità prevale l’ID in ordine alfabetico. Percentuali: totale 100 oppure tutto 0. Densità 0 disattiva gli spawn delegati; gli NPC manuali restano.</p></section>
<section id="world-properties"><h2>Progetto</h2><div class="fields">${field('seed', 'Seed procedurale')}<button id="seed-update">Aggiorna seed</button></div><h3>Zone definite</h3><div id="zone-list" class="selection-list"></div><h3>Controllo progetto</h3><button id="validate" class="wide">Verifica ingombri e riferimenti</button><ul id="issues"></ul><p class="hint">La bozza viene salvata localmente. “Applica al gioco” aggiorna il progetto a server fermo, con backup. Ricompila e riavvia il gioco dopo l’applicazione.</p></section></aside></main>
<footer class="status-bar"><span id="status" role="status">Caricamento progetto…</span><span id="save-state">Bozza locale</span><span>48 unità / casella</span></footer><input id="asset-files" type="file" accept="image/png,image/svg+xml,.png,.svg" multiple hidden><input id="world-file" type="file" accept=".json,application/json" hidden>
<dialog id="goto-dialog"><h2>Vai a una posizione</h2><p class="hint">Coordinate in quadratini, anche negative.</p><div class="pair">${field('goto-x', 'X')}${field('goto-y', 'Y')}</div><div class="dialog-actions"><button id="goto-confirm" class="primary">Vai</button><button id="goto-close">Annulla</button></div></dialog>`;
