import { test, expect } from '@playwright/test';
import type { InputCommand } from '../../shared/types';

test('menu options: conflicts, persistence, reset, narrow layout and in-game lock', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await page.locator('[data-binding="q-0"]').click(); await page.keyboard.press('KeyW');
  await expect(dialog.getByRole('status')).toContainText('Già assegnato');
  await page.keyboard.press('KeyF');
  await page.getByLabel('Modalità di movimento').selectOption('mouse');
  await expect(page.locator('[data-binding="basic-1"]')).toHaveText('+ Alternativo');
  await page.getByRole('button', { name: 'Salva controlli' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await expect(page.getByLabel('Modalità di movimento')).toHaveValue('mouse');
  await expect(page.locator('[data-binding="q-0"]')).toHaveText('F');
  await page.screenshot({ path: 'test-results/controls-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Salva controlli' })).toBeInViewport();
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/controls-mobile.png' });
  await page.getByRole('button', { name: 'Ripristina predefiniti' }).click();
  await expect(page.getByLabel('Modalità di movimento')).toHaveValue('keyboard');
  await expect(page.locator('[data-binding="q-0"]')).toHaveText('Q');
  await page.getByRole('button', { name: 'Annulla', exact: true }).click();
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await expect(page.getByLabel('Modalità di movimento')).toHaveValue('mouse');
  await page.getByRole('button', { name: 'Ripristina predefiniti' }).click();
  await page.getByRole('button', { name: 'Salva controlli' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await expect(page.locator('[data-binding="basic-1"]')).toHaveText('Mouse destro');
  await page.getByRole('button', { name: 'Chiudi opzioni' }).click();
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.locator('[data-ref="tab-register"]').click();
  await page.locator('[data-ref="name"]').fill(`Keys${Date.now().toString(36)}`);
  await page.locator('[data-ref="password"]').fill('controls-test-password');
  await page.locator('[data-ref="join"]').click();
  await expect(page.locator('.game-hud')).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('button', { name: 'Opzioni', exact: true })).toBeHidden();
  await expect(dialog).not.toBeVisible();
  await page.locator('[data-ref="leave"]').click();
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await expect(dialog).toBeVisible(); expect(errors).toEqual([]);
});

test('configured commands reach the simulation and release on blur and mouse up', async ({ page }) => {
  let input: InputCommand | undefined;
  const sent: InputCommand[] = [];
  page.on('websocket', socket => socket.on('framesent', frame => {
    const message = JSON.parse(String(frame.payload));
    if (message.type === 'input') { input = message.input; sent.push(message.input); }
  }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await page.getByLabel('Modalità di movimento').selectOption('mouse');
  await page.locator('[data-binding="q-0"]').click(); await page.keyboard.press('KeyF');
  await page.getByRole('button', { name: 'Salva controlli' }).click();
  await page.locator('[data-ref="tab-register"]').click();
  await page.locator('[data-ref="name"]').fill(`Input${Date.now().toString(36)}`);
  await page.locator('[data-ref="password"]').fill('controls-test-password');
  await page.locator('[data-ref="join"]').click();
  await expect(page.locator('.game-hud')).toBeVisible({ timeout: 30000 });
  await expect(page.locator('[data-slot="q"] kbd')).toHaveText('F');
  await page.mouse.move(900, 480); await page.mouse.down({ button: 'right' });
  await expect.poll(() => input?.dx ?? 0).toBeGreaterThan(0.5);
  expect(input?.cast).toBeUndefined();
  await page.mouse.up({ button: 'right' });
  await expect.poll(() => input?.dx).toBe(0);
  await page.keyboard.down('Space'); await expect.poll(() => input?.cast).toBe('basic');
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await expect.poll(() => input?.cast).toBeUndefined(); await page.keyboard.up('Space');
  await page.locator('[data-ref="leave"]').click();
  await page.getByRole('button', { name: 'Opzioni', exact: true }).click();
  await page.getByLabel('Modalità di movimento').selectOption('keyboard');
  await page.locator('[data-binding="right-0"]').click(); await page.keyboard.press('KeyL');
  await page.getByRole('button', { name: 'Salva controlli' }).click();
  await page.locator('[data-ref="join"]').click(); await expect(page.locator('.game-hud')).toBeVisible();
  await page.keyboard.down('KeyL'); await expect.poll(() => input?.dx).toBe(1);
  await page.keyboard.up('KeyL'); await expect.poll(() => input?.dx).toBe(0);
  await page.keyboard.down('KeyD');
  // Several transmitted ticks establish that the old binding stays inactive.
  const start = sent.length;
  await expect.poll(() => sent.length - start).toBeGreaterThan(3);
  expect(sent.slice(start).every(command => command.dx === 0)).toBe(true);
  await page.keyboard.up('KeyD');
});
