import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { RoomManager } from '../../server/rooms';
import type { Account } from '../../server/store';
import { xpForLevel } from '../../shared/config';

test('betting panel: gold access, quote selection, tickets, spectator updates and mobile layout', async () => {
  const bundle = await build({ entryPoints: ['client/ui/betting-ui.ts'], bundle: true, write: false, format: 'iife', globalName: 'BettingModule', outfile: 'betting.js' });
  const manager = new RoomManager(undefined, 734291, 1_000_000);
  const accounts: Account[] = ['Arden', 'Lyra', 'Viewer'].map(name => ({ id: name, name, nameLower: name.toLowerCase(), salt: '', passwordHash: '', kills: 10, deaths: 4, xp: 0, gold: 100, friends: [], requests: [], lastSeen: 0 }));
  accounts.forEach(a => manager.connect(a, 'mage'));
  manager.global.awardXp(accounts[2].id, xpForLevel(19));
  for (let i = 0; i < 110; i++) manager.step(.1);
  const matchId = await manager.createMatch('arena', [[accounts[0].id], [accounts[1].id]]);
  const snapshot = manager.snapshotFor(accounts[2].id)!; snapshot.betting!.bookmakerNearby = true;
  const browser = await chromium.launch({ channel: process.platform === 'win32' ? 'chrome' : undefined, headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.setContent('<div class="rift-app"><div class="status-row"><div class="gold-counter">100 GOLD</div></div></div><style>body{margin:0;background:#172431;font-family:system-ui}.rift-app{position:relative;width:100vw;height:100vh}.status-row{position:absolute!important;right:24px;top:24px;color:#e7c577}</style>');
    await page.addStyleTag({ content: bundle.outputFiles.find(f => f.path.endsWith('.css'))!.text });
    await page.addScriptTag({ content: bundle.outputFiles.find(f => f.path.endsWith('.js'))!.text });
    await page.evaluate(snapshot => {
      const w = window as any; w.actions = [];
      w.bettingUI = new w.BettingModule.BettingUI(document.querySelector('.rift-app'), (action: unknown) => w.actions.push(action), () => {});
      w.bettingUI.update(snapshot);
    }, snapshot);
    await page.getByRole('button', { name: 'Gold e scommesse attive' }).click();
    await expect(page.getByText('Nessuna puntata ancora.', { exact: false })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Duelli & quote' })).toHaveCount(0);
    await expect(page.locator('.arena-market')).toHaveCount(0);
    await page.getByRole('button', { name: 'Chiudi scommesse' }).click();
    await page.getByRole('button', { name: 'Assisti alle arene' }).click();
    await expect(page.locator('.arena-watch-card')).toBeVisible();
    await expect(page.getByLabel('Puntata in gold')).toHaveCount(0);
    await page.getByRole('button', { name: '◉ Assisti al duello' }).click();
    assert.deepEqual(await page.evaluate(() => (window as any).actions.pop()), { kind: 'watch', matchId });
    await page.evaluate(() => (window as any).bettingUI.open('markets'));
    await page.getByRole('button', { name: /Lyra/ }).click();
    await page.getByLabel('Puntata in gold').fill('25');
    mkdirSync(resolve('test-results'), { recursive: true });
    await page.screenshot({ path: resolve('test-results/betting-desktop.png') });
    await page.getByRole('button', { name: 'Conferma puntata' }).click();
    assert.deepEqual(await page.evaluate(() => (window as any).actions[0]), { kind: 'bet', matchId, playerId: 'Lyra', stake: 25 });
    snapshot.gold = 75;
    snapshot.betting!.bets = [{ id: 'ticket', matchId, playerId: 'Lyra', playerName: 'Lyra', stake: 25, odds: 1.89, payout: 0, status: 'active', placedAt: snapshot.time }];
    await page.evaluate(snapshot => (window as any).bettingUI.update(snapshot), snapshot);
    await page.getByRole('button', { name: 'Chiudi scommesse' }).click();
    await page.getByRole('button', { name: 'Gold e scommesse attive' }).click();
    await expect(page.getByText('IN CORSO', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '◉ Assisti al duello' }).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    assert.equal(await page.evaluate(() => (window as any).actions.at(-1).kind), 'watch');
    snapshot.betting!.spectating = matchId; snapshot.betting!.startsAt = snapshot.time + 10000;
    snapshot.actors = manager.snapshotFor(accounts[0].id)!.actors;
    await page.evaluate(snapshot => (window as any).bettingUI.update(snapshot), snapshot);
    const exit = page.getByRole('button', { name: 'Esci dalla tribuna' });
    await expect(exit).toBeVisible();
    // A snapshot between pointerdown and pointerup must not replace the exit button.
    await exit.dispatchEvent('pointerdown');
    snapshot.time += 100;
    await page.evaluate(snapshot => (window as any).bettingUI.update(snapshot), snapshot);
    await exit.click();
    assert.equal(await page.evaluate(() => (window as any).actions.at(-1).kind), 'exit');
    await page.screenshot({ path: resolve('test-results/betting-spectator.png') });
    snapshot.betting!.spectating = undefined; snapshot.betting!.startsAt = undefined;
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(snapshot => { (window as any).bettingUI.update(snapshot); (window as any).bettingUI.open('markets'); }, snapshot);
    await expect(page.getByRole('dialog')).toBeVisible();
    assert.ok(await page.getByRole('dialog').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
    await page.screenshot({ path: resolve('test-results/betting-mobile.png') });
    await page.getByRole('button', { name: 'Chiudi scommesse' }).click();
    await page.evaluate(() => (window as any).bettingUI.win({ id: 'win-safe', amount: 1234, celebrate: true }));
    await expect(page.locator('.bet-win-receipt')).toHaveText('WIN + 1234 GOLD');
    await expect(page.locator('.bet-win-overlay')).toBeVisible();
    await expect(page.locator('.bet-win-count')).toHaveText('+1234');
    await page.screenshot({ path: resolve('test-results/betting-win.png') });
    await page.getByRole('button', { name: 'Continua' }).click();
    snapshot.betting!.inCombat = true;
    await page.evaluate(snapshot => (window as any).bettingUI.update(snapshot), snapshot);
    await page.evaluate(() => (window as any).bettingUI.win({ id: 'win-combat', amount: 50, celebrate: false }));
    await expect(page.locator('.bet-win-receipt')).toHaveText('WIN + 1284 GOLD');
    await expect(page.locator('.bet-win-overlay')).toBeHidden();
    await page.evaluate(() => (window as any).bettingUI.win({ id: 'win-combat', amount: 50, celebrate: false }));
    await expect(page.locator('.bet-win-receipt')).toHaveText('WIN + 1284 GOLD');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
