import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'node:net';
import { once } from 'node:events';
import { chromium, expect, type Browser } from '@playwright/test';
import { AccountStore, characterFor, publicAccount } from '../../server/store';
import { WorldSimulation } from '../../server/simulation';
import { WORLD_DOCUMENT } from '../../shared/world-content';
import { TILE_SIZE } from '../../shared/config';
import { insertItem } from '../../shared/items';

test('real menu saves paid builds, class levels stay independent and quest XP animates by the HUD bar', { timeout: 90_000 }, async () => {
  const directory = mkdtempSync(join(tmpdir(), 'riftlands-progression-browser-'));
  const store = new AccountStore(join(directory, 'accounts.json')), sim = new WorldSimulation(734291, Date.now(), store);
  const user = store.register('ProgressionPlayer', 'test-password'), mage = characterFor(user.account, 'mage');
  mage.xp = 90; user.account.gold = 50;
  mage.narrative.quests['stinking-bait'] = { status: 'active', objectives: {} }; insertItem(mage.inventory, 'slime-innards', 3);
  const npc = WORLD_DOCUMENT.npcs.find(n => n.npcKind === 'old-fisher')!;
  const body = sim.addPlayer(user.account, 'mage');
  Object.assign(body, { x: (npc.x + .5) * TILE_SIZE - 48, y: (npc.y + .5) * TILE_SIZE, spawnProtectedUntil: Date.now() + 120_000 });
  sim.checkpoint(); store.flush();
  const probe = createServer(); probe.listen(0, '127.0.0.1'); await once(probe, 'listening');
  const port = (probe.address() as { port: number }).port; await new Promise<void>(done => probe.close(() => done()));
  const child = spawn(process.execPath, ['--import', 'tsx', 'server/index.ts'], { cwd: resolve('.'), windowsHide: true,
    env: { ...process.env, PORT: String(port), HOST: '127.0.0.1', DATA_FILE: store.path, NODE_ENV: 'development' }, stdio: ['ignore', 'pipe', 'pipe'] });
  const ended = once(child, 'close'); let browser: Browser | undefined, log = '';
  child.stderr.on('data', data => { log += String(data); });
  try {
    await new Promise<void>((done, reject) => {
      const timer = setTimeout(() => reject(new Error('Startup timeout: ' + log)), 15000);
      child.stdout.on('data', data => { if (String(data).includes('Riftlands:')) { clearTimeout(timer); done(); } });
      child.once('error', error => { clearTimeout(timer); reject(error); }); child.once('exit', code => { clearTimeout(timer); reject(new Error(`Server exit ${code}: ${log}`)); });
    });
    browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL ?? 'chrome', headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await context.addInitScript(({ token, profile }) => { localStorage.setItem('riftlands.jwt', token); localStorage.setItem('riftlands.profile', JSON.stringify(profile)); localStorage.setItem('riftlands.selected-class', 'mage'); }, { token: user.token, profile: publicAccount(user.account) });
    const page = await context.newPage(), errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    const origin = `http://127.0.0.1:${port}`, headers = { Authorization: 'Bearer ' + user.token };
    await page.goto(origin); await expect(page.locator('[data-ref=build-editor]')).toContainText('Livello 1');
    await expect(page.locator('[data-class=hunter] .class-level')).toHaveText('LV 20');
    await page.locator('[data-class=hunter]').click();
    await expect(page.locator('[data-ref=build-editor]')).toContainText('Livello 20');
    const q = page.locator('[data-build-slot=q]'), e = page.locator('[data-build-slot=e]');
    const choose = async (id: string) => { await q.click(); await page.locator(`.spell-choice[data-spell=${id}]`).click(); await expect(page.locator('.build-picker')).toHaveCount(0); };
    const desktopBuild = await page.locator('[data-ref=build-editor]').boundingBox();
    assert.ok(desktopBuild && desktopBuild.width > 700, 'desktop build spans the broad character workspace');
    const desktopPlay = await page.locator('[data-ref=join]').boundingBox(), desktopPortrait = await page.locator('[data-ref=champion-portrait]').boundingBox();
    assert.ok(desktopPlay && desktopPortrait && desktopPlay.y >= desktopPortrait.y + desktopPortrait.height && desktopPlay.y + desktopPlay.height <= desktopBuild.y, 'Play sits immediately under the character, before the skill build');
    mkdirSync('test-results', { recursive: true });
    await q.click(); await expect(page.locator('.spell-choice')).toHaveCount(3);
    await page.screenshot({ path: 'test-results/progression-wheel-desktop.png' });
    await page.keyboard.press('Escape'); await expect(page.locator('.build-picker')).toHaveCount(0); await expect(q).toBeFocused();
    await expect(q).toHaveAttribute('data-spell', 'q');
    await choose('r'); await page.getByRole('button', { name: 'Salva build · Gratis', exact: true }).click();
    await expect(q).toHaveAttribute('data-spell', 'r');
    await choose('q'); await page.getByRole('button', { name: 'Salva build · 10 gold', exact: true }).click();
    await expect(page.locator('[data-ref=lobby-gold]')).toHaveText('40');
    await choose('e'); await expect(e).toHaveAttribute('data-spell', 'q');
    await page.getByRole('button', { name: 'Salva build · Gratis', exact: true }).click();
    await expect(q).toHaveAttribute('data-spell', 'e'); await expect(page.locator('[data-ref=lobby-gold]')).toHaveText('40');
    const invalid = await page.request.post(origin + '/api/build', { headers, data: { classId: 'mage', loadout: { q: 'r', e: 'e' } } }); assert.equal(invalid.status(), 400);
    await expect(page.getByRole('button', { name: 'Salva build · Gratis', exact: true })).toBeVisible();
    await page.evaluate(() => { document.querySelector('.camp-content')!.scrollTop = 0; });
    await page.screenshot({ path: 'test-results/progression-build-desktop.png' });
    for (const width of [1024, 1280, 1920]) {
      await page.setViewportSize({ width, height: 900 });
      const box = await page.locator('[data-ref=build-editor]').boundingBox();
      assert.ok(box && box.width > 500 && box.x >= 0 && box.x + box.width <= width, `${width}px desktop build has a wide workspace inside the viewport`);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('[data-class=mage]').click(); await expect(page.locator('[data-ref=build-editor]')).toContainText('Livello 1');
    await expect(q).toBeDisabled(); await expect(e).toBeDisabled();
    await page.locator('[data-ref=join]').click(); await expect(page.locator('[data-ref=world-entrance]')).toBeHidden(); await expect(page.locator('.game-hud')).toBeVisible();
    await expect(page.locator('.ability-bar [data-slot]')).toHaveCount(2);
    const online = await page.request.post(origin + '/api/build', { headers, data: { classId: 'hunter', loadout: { q: 'q', e: 'r' } } }); assert.equal(online.status(), 400);
    await page.keyboard.press('KeyF'); await expect(page.locator('.npc-dialogue')).toBeVisible();
    await page.locator('.backpack-toggle').click(); await page.locator('.inventory-slot').click(); await expect(page.locator('.xp-gain')).toHaveText('+150 XP');
    await expect(page.locator('.gold-gain')).toHaveText('+20 GOLD');
    const gainBounds = await page.locator('.xp-gain').boundingBox(), resourceBounds = await page.locator('[data-ref=resource-fill]').boundingBox();
    assert.ok(gainBounds && resourceBounds && gainBounds.y >= resourceBounds.y + resourceBounds.height, 'XP gain sits below the vitals without covering them');
    await expect(page.locator('.level-up-number')).toHaveText('3');
    await expect(page.locator('.xp-level-up')).toBeVisible();
    assert.ok(await page.locator('.xp-confetti>i').count() > 0, 'level gain emits particles at the XP meter');
    const center = await page.locator('.xp-level-up').boundingBox();
    assert.ok(center && Math.abs(center.x + center.width / 2 - 720) < 5 && center.y + center.height < 500, 'level celebration stays above the player');
    assert.equal(await page.locator('.xp-level-up').evaluate(node => getComputedStyle(node).pointerEvents), 'none', 'celebration preserves gameplay input');
    await page.waitForTimeout(160); // Capture the visible burst after the entry frames.
    await page.screenshot({ path: 'test-results/progression-xp-desktop.png' });
    await expect(page.locator('[data-ref=player-level]')).toHaveText('3'); await expect(page.locator('[data-ref=hud-gold]')).toHaveText('60');
    const levelBadge = await page.locator('[data-ref=player-level]').boundingBox(), portraitBox = await page.locator('[data-ref=portrait]').boundingBox();
    assert.ok(levelBadge && portraitBox && levelBadge.width <= 24 && levelBadge.height === levelBadge.width && Math.abs(levelBadge.x + levelBadge.width / 2 - (portraitBox.x + portraitBox.width / 2)) < 1 && levelBadge.y >= portraitBox.y + portraitBox.height - 16, 'level is a small circle on the lower edge of the portrait');
    assert.equal(await page.locator('[data-ref=player-level]').evaluate(node => getComputedStyle(node).borderRadius), '50%');
    assert.equal(await page.locator('[data-ref=player-level]').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(23, 41, 53)');
    await page.waitForTimeout(1400); await expect(page.locator('.xp-level-up')).toBeVisible();
    await expect(page.locator('.xp-level-up')).toBeHidden(); await expect(page.locator('.xp-confetti>i')).toHaveCount(0);
    const state = await page.request.get(origin + '/api/lobby?classId=mage', { headers }), data = await state.json();
    assert.equal(data.account.characters.mage.xp, 240); assert.equal(data.account.characters.warrior.xp, 0); assert.equal(data.narrative.quests['stinking-bait'].completions, 1);
    // Exercise compact HUD and the same editor on a narrow touch viewport.
    const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
    await mobile.addInitScript(({ token }) => { localStorage.setItem('riftlands.jwt', token); localStorage.setItem('riftlands.selected-class', 'hunter'); }, { token: user.token });
    const mobilePage = await mobile.newPage(); mobilePage.on('pageerror', error => errors.push(error.message)); await mobilePage.goto(origin);
    await expect(mobilePage.locator('[data-ref=menu-boot]')).toBeHidden();
    await expect(mobilePage.locator('[data-ref=build-editor]')).toContainText('Livello 20');
    const bounds = await mobilePage.locator('[data-ref=build-editor]').boundingBox(); assert.ok(bounds && bounds.x >= 0 && bounds.x + bounds.width <= 391);
    const mobilePlay = await mobilePage.locator('[data-ref=join]').boundingBox(), mobilePortrait = await mobilePage.locator('[data-ref=champion-portrait]').boundingBox();
    assert.ok(mobilePlay && mobilePortrait && mobilePlay.y >= mobilePortrait.y + mobilePortrait.height && mobilePlay.y + mobilePlay.height < bounds.y, 'touch Play is also immediately beneath the character and before the build');
    await mobilePage.locator('[data-ref=build-editor]').scrollIntoViewIfNeeded(); await mobilePage.screenshot({ path: 'test-results/progression-build-mobile.png' });
    await mobilePage.locator('[data-build-slot=q]').click();
    const wheel = await mobilePage.locator('.build-picker').boundingBox(); assert.ok(wheel && wheel.x >= 0 && wheel.x + wheel.width <= 391 && wheel.y >= 0 && wheel.y + wheel.height <= 845);
    await mobilePage.screenshot({ path: 'test-results/progression-wheel-mobile.png' });
    await mobilePage.locator('.build-picker-close').click(); await expect(mobilePage.locator('.build-picker')).toHaveCount(0);
    await mobilePage.setViewportSize({ width: 844, height: 390 });
    await mobilePage.locator('[data-build-slot=q]').click();
    const landscapeWheel = await mobilePage.locator('.build-picker').boundingBox();
    assert.ok(landscapeWheel && landscapeWheel.x >= 0 && landscapeWheel.x + landscapeWheel.width <= 845 && landscapeWheel.y >= 0 && landscapeWheel.y + landscapeWheel.height <= 391);
    await mobilePage.screenshot({ path: 'test-results/progression-wheel-landscape.png' });
    await mobilePage.locator('.build-picker-close').click(); await expect(mobilePage.locator('.build-picker')).toHaveCount(0);
    await page.locator('.map-toggle').click(); await page.locator('[data-ref=leave]').click(); await page.locator('[data-exit]').click();
    await expect(page.locator('.game-hud')).toBeHidden();
    await expect(page.locator('[data-ref=build-editor]')).toContainText('Livello 3');
    await q.click(); await expect(page.locator('.spell-choice[data-spell=r]')).toBeDisabled();
    await page.locator('.spell-choice[data-spell=e]').click(); await expect(q).toHaveAttribute('data-spell', 'e');
    await page.getByRole('button', { name: 'Annulla', exact: true }).click(); await expect(q).toHaveAttribute('data-spell', 'q');
    // Feedback lifecycle: no fake gain on entry, reduced motion and session reset.
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.evaluate(async () => {
      const { XpFeedback } = await import('/client/ui/hud/xp-feedback.ts' as string);
      const fixture = document.createElement('div'); fixture.className = 'game-hud xp-review';
      fixture.innerHTML = '<span class="review-level"></span><div class="xp-meter"><i></i></div>';
      document.querySelector('#app')!.append(fixture);
      const feedback = new XpFeedback(fixture.querySelector('i')!, fixture.querySelector('.review-level')!);
      (window as any).xpReview = { feedback, fixture };
      feedback.update('first', 99);
    });
    await expect(page.locator('.xp-review .xp-gain')).toBeHidden(); await expect(page.locator('.xp-review .xp-level-up')).toBeHidden();
    await page.evaluate(() => (window as any).xpReview.feedback.update('first', 100));
    await expect(page.locator('.xp-review .level-up-number')).toHaveText('2');
    await expect(page.locator('.xp-review .xp-confetti>i')).toHaveCount(0);
    await expect(page.locator('.xp-review .review-level')).toHaveText('2');
    await page.evaluate(() => (window as any).xpReview.feedback.update('other-character', 8740));
    await expect(page.locator('.xp-review .review-level')).toHaveText('20');
    await expect(page.locator('.xp-review .xp-level-up')).toBeHidden();
    await expect(page.locator('.xp-review .xp-gain')).toBeHidden();
    await page.evaluate(() => { const { feedback, fixture } = (window as any).xpReview; feedback.reset(); fixture.remove(); });
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close(); child.kill(); await ended; rmSync(directory, { recursive: true, force: true });
  }
});
